name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install buildozer cython==0.29.33
          sudo apt update
          sudo apt install -y openjdk-17-jdk zip unzip libltdl-dev libffi-dev libssl-dev libbz2-dev
      - name: Build APK
        run: |
          yes | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: bin/*.apk
